#!/usr/bin/env bash

echo "Running tests before push..."

# use py inside .venv to run pytest
./.venv/bin/python -m pytest

# store exit code form pytest
TEST_EXIT_CODE=$?

# on failing tests (non-zero exit code) push is aborted
if [ $TEST_EXIT_CODE -ne 0 ]; then
  echo "Tests failed. Aborting push."
  exit 1
fi

# on success exiting with zero to continue push
echo "All tests passed. Proceeding with push."
exit 0

